### ISSUE TITLE
Wrong message at console target

### ISSUE THREAD

**Issue by mluizaa00** [SaiintBrisson/command-framework#10]
When a player use a command that is only enabled for **CONSOLE**, it shows the error: "Only players can execute this command" 

Instead it should be "Only console can execute this command"

**Comment by saiintbrisson** [comment]
Found the issue, I'll see what I can do about it, although I'm a bit unsure of what I can do to fix it. I'll let you know as soon as I figure this out.

**Comment by mluizaa00** [comment]
Actually wasn't a issue, just didn't add the placeholder {target}.
A documentation for the MessageHolder was added as well description about placeholders because of that.
