### ISSUE TITLE
Project not identifying the framework

### ISSUE THREAD

**Issue by Shouzza** [SaiintBrisson/command-framework#11]
Literally I added the framework extension to my gradle and used it, more when I compile the plugin it gives an error on the console.

Below I will send some images of what happened.

![carbon (5)](https://user-images.githubusercontent.com/50285920/114552780-53ed5b80-9c3b-11eb-9493-1fef118821a9.png)
![carbon (6)](https://user-images.githubusercontent.com/50285920/114553320-e5f56400-9c3b-11eb-8887-611ccc98af0b.png)
![carbon (7)](https://user-images.githubusercontent.com/50285920/114553484-0e7d5e00-9c3c-11eb-94e1-484282948ac4.png)

**Comment by saiintbrisson** [comment]
I don't think this is on my end, have you tried running the shadowJar task?
